### ISSUE TITLE
Page latex formatting broken on latest Chrome and Firefox

### ISSUE THREAD

**Issue by Piruzzolo** [MicrosoftDocs/quantum-docs-pr.it-IT#1]
As title

---
#### Dettagli del documento

⚠ *Non modificare questa sezione. È necessaria per i collegamenti relativi ai problemi tra docs.microsoft.com ➟ GitHub.*

* ID: 434e640f-ea90-3c49-9510-1fda8cbee7a1
* Version Independent ID: 9c5af71d-7980-d644-b2bc-9b54bda5e551
* Content: [Vettori e matrici - Microsoft Quantum](https://docs.microsoft.com/it-it/quantum/concepts/vectors-and-matrices?view=qsharp-preview#feedback)
* Content Source: [articles/concepts/vectors-and-matrices.md](https://github.com/MicrosoftDocs/quantum-docs-pr.it-IT/blob/live-sxs/articles/concepts/vectors-and-matrices.md)
* Product: **quantum**
* GitHub Login: @QuantumWriter
* Microsoft Alias: **nawiebe@microsoft.com**

**Comment by srvbpigh** [comment]
Hello, @Piruzzolo
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by ticianaciminari** [comment]
Hello, @Piruzzolo, 

Your contribution is much appreciated. Our team can only answer feedback related to the documentation. 

Please kindly log your product feedback by using the button "Give Product Feedback" at the bottom of the DOCS page. 

If you have any feedback related to the documentation, please feel free to log it through this channel. 

We truly appreciate your contribution to our articles.  

Kind regards, 

Microsoft DOCS International Team
